### ISSUE TITLE
Web server does not appear to be running

### ISSUE THREAD

**Issue by Rich2020** [krakenrf/krakensdr_pr#6]
Firstly, congratulations on such an amazing product! The kit is very well built and the installation instructions are flawless!

I am trying to get my KrakenSDR set up on a Raspberry Pi 4, running the latest Ubuntu (22.10, 64-bit).
I followed all instructions in this PR repo and in the HeIMDALL DAQ Firmware repo, taking the manual installation approach, without issues or errors.
I've rebooted my Pi.

My directory structure is:
```
home
    - krakensdr
        - kraken_pr_start.sh
        - kraken_pr_stop.sh
        - krakensdr_pr
        - heimdall_daq_fw 
```

When I run  `./kraken_pr_start.sh`, I get the following output:
        
```
Shut down DAQ chain ..
Config file check bypassed [ WARNING ]
kernel.sched_rt_runtime_us = -1
Desig FIR filter with the following parameters: 
Decimation ratio: 1
Bandwidth: 1.00
Tap size: 1
Window function: hann
FIR filter ready
Transfer funcfion is exported to :  _logs/Decimator_filter_transfer.html
Coefficients are exported to:  _data_control/fir_coeffs.txt
Starting DAQ Subsystem
Output data interface: Shared memory
    
[some coffee graphic]
                       
Have a coffee watch radar
Starting KrakenSDR Passive Radar
```

And then the terminal returns to the prompt. 
Using a web browser, I have tried (on the Pi) to visit localhost:8080, 127.0.0.1:8080, 0.0.0.0:8080 and kraken-pi4:8080 (using hostname). None of them work, all saying that the server cannot be found.

What is going on? Why am I unable to visit the web GUI?

### UPDATE
It turns out that the dependencies are broken. The manual install will not work until the dependencies are fixed. A temp solution is to copy the virtual environment from the e.g., raspberry pi image, to the system running the manual installation.

**Comment by krakenrf** [comment]
What dependencies are broken? I just did a manual install with the script a couple of weeks ago and it went well. Everything sensitive to updates should already be pinned to working versions.

**Comment by krakenrf** [comment]
Oh I see you're doing a manual install without the script. I think the readme hasn't been updated since we started using the script for manual installs. I'll update the readme now.

**Comment by Rich2020** [comment]
Thank you!
